import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  standalone: true,
  selector: 'app-landing',
  imports: [RouterLink],
  template: `
    <div class="landing-shell">
      <header class="landing-header">
        <a class="brand" href="#start" aria-label="Reals home"><span>R</span>reals</a>
        <p class="page-count"><strong>01</strong> / 05</p>
        <div class="header-actions">
          <a routerLink="/auth/login">Đăng nhập</a>
          <a class="header-register" routerLink="/auth/register">Đăng ký <span>↗</span></a>
        </div>
      </header>

      <main class="horizontal-track" id="start">
        <section class="panel panel-intro" aria-labelledby="intro-title">
          <div class="intro-copy">
            <p class="kicker">Social / commerce / culture</p>
            <h1 id="intro-title">Một nơi<br /><em>để là mình.</em></h1>
            <p class="lead">Reals kết nối những điều bạn yêu thích với những người cũng đang tìm kiếm chúng.</p>
            <a class="primary-button" routerLink="/auth/register">Bắt đầu khám phá <span>↗</span></a>
          </div>
          <div class="intro-art" aria-hidden="true"><div class="art-circle"></div><div class="art-card art-card-back">share<br />what<br /><em>matters</em></div><div class="art-card art-card-front"><span>REAL<br />PEOPLE<br />REAL<br /><em>STORIES</em></span><b>↗</b></div><span class="art-star">✦</span></div>
          <p class="scroll-hint"><span>01</span> Kéo sang để khám phá <b>→</b></p>
        </section>

        <section class="panel panel-about" aria-labelledby="about-title">
          <div class="panel-index">02 <span>/ what is reals</span></div>
          <div class="about-content"><p class="kicker">Made for real life</p><h2 id="about-title">Không chỉ<br /><em>là một feed.</em></h2><p class="body-copy">Đây là không gian để những cuộc trò chuyện, video, câu chuyện và món đồ bạn yêu thích cùng tồn tại.</p><div class="feature-list"><div><strong>01</strong><span><b>Connect</b><small>Gặp những người cùng tần số.</small></span></div><div><strong>02</strong><span><b>Discover</b><small>Mỗi lần lướt là một điều mới.</small></span></div><div><strong>03</strong><span><b>Create</b><small>Chia sẻ góc nhìn của bạn.</small></span></div></div></div>
          <div class="about-note"><span>✦</span><p>designed<br />for your<br /><em>everyday</em></p></div>
        </section>

        <section class="panel panel-auth" aria-labelledby="auth-title">
          <div class="panel-index">03 <span>/ join reals</span></div>
          <div class="auth-content"><p class="kicker">Your space is ready</p><h2 id="auth-title">Bắt đầu<br /><em>từ hôm nay.</em></h2><p class="body-copy">Đăng nhập để tiếp tục hành trình, hoặc tạo tài khoản mới trong vài giây.</p><div class="auth-actions"><a class="primary-button" routerLink="/auth/register">Tạo tài khoản <span>↗</span></a><a class="auth-secondary" routerLink="/auth/login">Đăng nhập <span>→</span></a></div></div>
          <div class="auth-card"><span>reals</span><strong>real people.<br />real stories.</strong><small>01 / welcome in</small></div>
        </section>

        <section class="panel panel-spaces" aria-labelledby="spaces-title">
          <div class="panel-index">04 <span>/ one platform</span></div>
          <div class="spaces-heading"><p class="kicker">Four ways to feel at home</p><h2 id="spaces-title">Bạn muốn<br /><em>đi đâu trước?</em></h2></div>
          <div class="space-list"><a routerLink="/social"><span>01</span><b>Social</b><small>Những cuộc trò chuyện thật</small><i>↗</i></a><a routerLink="/video"><span>02</span><b>Video</b><small>Nội dung làm bạn dừng lại</small><i>↗</i></a><a routerLink="/shop"><span>03</span><b>Shop</b><small>Món đồ có câu chuyện</small><i>↗</i></a><a routerLink="/stories"><span>04</span><b>Stories</b><small>Những điều đáng được kể</small><i>↗</i></a></div>
        </section>

        <section class="panel panel-portfolio" aria-labelledby="portfolio-title">
          <div class="portfolio-label">05 / portfolio</div>
          <div class="portfolio-content"><p class="kicker">Developer portfolio</p><h2 id="portfolio-title">Building<br /><em>what matters.</em></h2><p class="body-copy">Backend Engineer xây dựng scalable APIs, distributed systems và hạ tầng đáng tin cậy.</p><div class="portfolio-stats"><span><b>03</b><small>selected projects</small></span><span><b>04</b><small>core disciplines</small></span><span><b>01</b><small>clear point of view</small></span></div><a class="portfolio-button" [href]="portfolioUrl" target="_blank" rel="noreferrer">Mở portfolio đầy đủ <span>↗</span></a></div>
          <div class="portfolio-mark" aria-hidden="true"><span>R</span><b>systems<br />with<br />purpose</b></div>
        </section>
      </main>
      <p class="mobile-scroll-note">Vuốt ngang để khám phá <span>→</span></p>
    </div>
  `,
  styles: [`
    :host { display: block; min-height: 100vh; }
    .landing-shell { --ink: #20201d; --cream: #f5f1e9; --orange: #ed694e; --lime: #cbd96a; min-height: 100vh; overflow: hidden; background: var(--cream); color: var(--ink); font-family: 'Outfit', sans-serif; }
    .landing-header { position: fixed; z-index: 5; top: 0; left: 0; width: 100%; height: 78px; display: flex; align-items: center; justify-content: space-between; padding: 0 5vw; mix-blend-mode: multiply; }
    .brand { color: var(--ink); font-size: 1.3rem; font-weight: 700; letter-spacing: -.07em; text-decoration: none; }.brand span { display: inline-grid; place-items: center; width: 28px; height: 28px; margin-right: 4px; border-radius: 50%; background: var(--orange); color: white; font-size: .9rem; letter-spacing: 0; }
    .page-count { margin: 0; font-size: .7rem; letter-spacing: .12em; }.page-count strong { color: var(--orange); }.header-actions { display: flex; align-items: center; gap: 24px; }.header-actions a { color: var(--ink); font-size: .74rem; text-decoration: none; }.header-register { padding: 10px 15px; border: 1px solid rgba(32,32,29,.3); border-radius: 99px; }.header-register span, .primary-button span, .portfolio-button span { margin-left: 9px; }
    .horizontal-track { display: flex; width: 500vw; height: 100vh; overflow-x: auto; overflow-y: hidden; scroll-snap-type: x mandatory; scrollbar-width: none; }.horizontal-track::-webkit-scrollbar { display: none; }.panel { position: relative; flex: 0 0 100vw; width: 100vw; height: 100vh; overflow: hidden; scroll-snap-align: start; padding: 140px 10vw 70px; }.panel h1, .panel h2 { margin: 0; font-weight: 500; letter-spacing: -.08em; line-height: .88; }.panel h1 { font-size: clamp(4.8rem, 9.7vw, 10rem); }.panel h2 { font-size: clamp(4rem, 8vw, 8.2rem); }.panel em { color: var(--orange); font-family: Georgia, serif; font-weight: 400; }.kicker { margin: 0 0 25px; color: var(--orange); font-size: .68rem; font-weight: 700; letter-spacing: .19em; text-transform: uppercase; }.lead, .body-copy { max-width: 360px; color: rgba(32,32,29,.62); font-size: .95rem; line-height: 1.65; }.lead { margin: 34px 0 31px; }.primary-button, .portfolio-button { display: inline-flex; align-items: center; width: fit-content; padding: 15px 20px; border-radius: 99px; background: var(--ink); color: white; font-size: .76rem; font-weight: 700; text-decoration: none; }.primary-button:hover, .portfolio-button:hover { transform: translateY(-2px); }
    .panel-intro { display: flex; align-items: center; justify-content: space-between; gap: 5vw; background: var(--cream); }.intro-copy { position: relative; z-index: 1; max-width: 620px; }.intro-art { position: relative; width: min(43vw, 560px); height: min(75vh, 630px); flex: 0 0 min(43vw, 560px); }.art-circle { position: absolute; top: 2%; left: 7%; width: 82%; aspect-ratio: 1; border-radius: 50%; background: var(--lime); }.art-card { position: absolute; display: flex; flex-direction: column; justify-content: space-between; padding: 25px; box-shadow: 18px 18px 0 rgba(32,32,29,.08); }.art-card-back { top: 11%; right: 5%; width: 47%; height: 43%; background: #dfc2a7; font-size: clamp(1.2rem, 2.3vw, 2.2rem); line-height: .95; transform: rotate(8deg); }.art-card-back em { color: var(--orange); }.art-card-front { bottom: 4%; left: 11%; width: 55%; height: 61%; background: var(--orange); color: white; transform: rotate(-7deg); }.art-card-front span { font-size: clamp(1.4rem, 3vw, 3.3rem); font-weight: 700; line-height: .88; }.art-card-front em { color: var(--lime); }.art-card-front b { align-self: flex-end; font-size: 2rem; font-weight: 400; }.art-star { position: absolute; right: 1%; bottom: 15%; color: var(--orange); font-size: 3rem; }.scroll-hint { position: absolute; bottom: 28px; left: 10vw; margin: 0; color: rgba(32,32,29,.55); font-size: .65rem; letter-spacing: .12em; text-transform: uppercase; }.scroll-hint span { color: var(--orange); margin-right: 13px; }.scroll-hint b { margin-left: 20px; color: var(--ink); font-size: 1.2rem; }
    .panel-index, .portfolio-label { position: absolute; top: 140px; left: 10vw; color: var(--orange); font-size: .67rem; font-weight: 700; letter-spacing: .16em; text-transform: uppercase; }.panel-index span { color: rgba(32,32,29,.45); margin-left: 8px; }.panel-about { background: #f0ceb5; }.about-content { margin: 105px auto 0; width: min(700px, 70vw); }.about-content .body-copy { margin: 35px 0 42px; }.feature-list { display: flex; gap: 35px; border-top: 1px solid rgba(32,32,29,.25); padding-top: 20px; }.feature-list > div { display: flex; gap: 13px; }.feature-list strong { color: var(--orange); font-size: .66rem; }.feature-list span { display: flex; flex-direction: column; gap: 5px; }.feature-list b { font-size: .8rem; }.feature-list small { color: rgba(32,32,29,.58); font-size: .67rem; }.about-note { position: absolute; right: 11vw; bottom: 19%; display: flex; align-items: center; gap: 10px; transform: rotate(7deg); }.about-note span { font-size: 3rem; color: var(--orange); }.about-note p { margin: 0; font-size: .78rem; line-height: 1.1; }.about-note em { color: var(--orange); }
    .panel-auth { display: flex; align-items: center; justify-content: center; gap: 12vw; background: #dfc2a7; }.auth-content .body-copy { margin: 30px 0; }.auth-actions { display: flex; align-items: center; gap: 24px; }.auth-secondary { color: var(--ink); font-size: .76rem; font-weight: 700; text-decoration: none; }.auth-secondary span { margin-left: 8px; color: var(--orange); }.auth-card { display: flex; flex-direction: column; justify-content: space-between; width: min(28vw, 290px); height: min(40vw, 390px); padding: 24px; background: var(--orange); color: white; transform: rotate(6deg); box-shadow: 15px 15px 0 rgba(32,32,29,.1); }.auth-card span { font-size: 1.1rem; font-weight: 700; letter-spacing: -.08em; }.auth-card strong { font-size: clamp(1.7rem, 3vw, 2.8rem); line-height: .9; letter-spacing: -.07em; }.auth-card small { color: var(--lime); font-size: .65rem; letter-spacing: .1em; text-transform: uppercase; }
    .panel-spaces { background: var(--lime); }.spaces-heading { margin: 105px 0 55px 14vw; }.spaces-heading h2 { color: var(--ink); }.spaces-heading em { color: var(--orange); }.space-list { width: min(720px, 70vw); margin-left: 14vw; border-top: 1px solid rgba(32,32,29,.32); }.space-list a { display: grid; grid-template-columns: 42px 1fr 1.4fr 30px; align-items: center; gap: 14px; padding: 17px 0; border-bottom: 1px solid rgba(32,32,29,.32); color: var(--ink); text-decoration: none; }.space-list a:hover b { color: var(--orange); }.space-list span, .space-list small { color: rgba(32,32,29,.57); font-size: .68rem; }.space-list b { font-size: 1.1rem; font-weight: 500; }.space-list i { font-size: 1.1rem; font-style: normal; text-align: right; }
    .panel-join { display: flex; align-items: center; justify-content: center; gap: 12vw; background: var(--orange); color: white; }.join-quote { width: 250px; transform: rotate(-7deg); }.join-quote span { display: block; color: var(--lime); font-family: Georgia, serif; font-size: 7rem; line-height: .5; }.join-quote p { margin: 15px 0; font-size: 2.2rem; font-weight: 500; letter-spacing: -.06em; line-height: .95; }.join-quote em { color: var(--lime); font-family: Georgia, serif; font-weight: 400; }.join-content .kicker { color: var(--lime); }.join-content h2 em { color: var(--lime); }.join-content .body-copy { margin: 30px 0; color: rgba(255,255,255,.73); }.join-actions { display: flex; align-items: center; gap: 25px; }.join-actions .primary-button { background: white; color: var(--ink); }.text-button { color: white; font-size: .75rem; text-decoration: none; }
    .panel-portfolio { display: flex; align-items: center; justify-content: space-between; background: var(--ink); color: var(--cream); }.portfolio-label { color: var(--lime); }.portfolio-content { margin-left: 12vw; }.portfolio-content .kicker { color: var(--lime); }.portfolio-content h2 em { color: var(--lime); }.portfolio-content .body-copy { margin: 25px 0; color: rgba(245,241,233,.62); }.portfolio-stats { display: flex; gap: 28px; margin: 0 0 25px; }.portfolio-stats span { display: flex; flex-direction: column; gap: 4px; }.portfolio-stats b { color: var(--lime); font-size: 1.25rem; font-weight: 500; }.portfolio-stats small { color: rgba(245,241,233,.5); font-size: .62rem; }.portfolio-button { background: var(--lime); color: var(--ink); }.portfolio-mark { position: relative; display: grid; place-items: center; width: min(34vw, 440px); aspect-ratio: 1; margin-right: 12vw; border: 1px solid rgba(203,217,106,.55); border-radius: 50%; transform: rotate(9deg); }.portfolio-mark span { color: var(--orange); font-size: 11rem; font-weight: 700; letter-spacing: -.15em; }.portfolio-mark b { position: absolute; right: 5%; bottom: 20%; color: var(--lime); font-size: .7rem; line-height: 1.1; text-transform: uppercase; }.mobile-scroll-note { display: none; }
    @media (max-width: 760px) { .landing-header { height: 64px; padding: 0 20px; }.page-count { display: none; }.header-actions { gap: 12px; }.header-actions a { font-size: .68rem; }.header-register { padding: 8px 10px; }.panel { padding: 105px 24px 55px; }.panel-intro { display: block; }.panel h1 { font-size: clamp(4rem, 18vw, 6.2rem); }.intro-art { width: 100%; height: 40vh; min-height: 250px; margin-top: 30px; }.art-card-front { width: 52%; height: 72%; }.art-card-back { height: 52%; }.scroll-hint { display: none; }.panel-index, .portfolio-label { top: 92px; left: 24px; }.about-content, .space-list { width: 100%; }.about-content { margin-top: 82px; }.panel h2 { font-size: clamp(3.3rem, 15vw, 5rem); }.feature-list { display: grid; gap: 15px; }.about-note { right: 12%; bottom: 8%; }.panel-auth { display: block; padding-top: 125px; }.auth-card { width: 170px; height: 220px; margin: 45px auto 0; }.auth-card strong { font-size: 1.6rem; }.auth-actions { align-items: flex-start; flex-direction: column; gap: 18px; }.spaces-heading { margin: 84px 0 36px; }.space-list { margin-left: 0; }.space-list a { grid-template-columns: 28px 1fr 30px; }.space-list small { display: none; }.panel-portfolio { display: block; padding-top: 135px; }.portfolio-content { margin-left: 0; }.portfolio-stats { gap: 16px; }.portfolio-stats small { max-width: 70px; }.portfolio-mark { width: 190px; margin: 35px auto 0; }.portfolio-mark span { font-size: 7rem; }.mobile-scroll-note { position: fixed; display: block; z-index: 4; bottom: 13px; left: 50%; margin: 0; padding: 7px 10px; border-radius: 99px; background: rgba(245,241,233,.8); color: rgba(32,32,29,.65); font-size: .63rem; transform: translateX(-50%); }.mobile-scroll-note span { margin-left: 5px; color: var(--orange); font-size: 1rem; } }
  `],
})
export class LandingComponent {
  readonly portfolioUrl = 'http://localhost:4301';
}
