import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '@fe/core';

@Component({
  standalone: true,
  selector: 'feat-home-page',
  imports: [CommonModule, RouterModule],
  template: `
    <div class="landing-page">
      <nav class="site-nav" aria-label="Điều hướng chính">
        <a class="wordmark" routerLink="/home" aria-label="Reals Platform home"><span>R</span>reals</a>
        <div class="nav-links"><a href="#spaces">Không gian</a><a href="#portfolio">Portfolio</a><a href="#about">Về Reals</a></div>
        <a class="nav-action" href="#spaces">Bắt đầu <span aria-hidden="true">↗</span></a>
      </nav>
      <main>
        <section class="hero" aria-labelledby="hero-title">
          <div class="hero-copy"><p class="eyebrow"><span class="eyebrow-dot"></span> Không gian của {{ userDisplayName }}</p><h1 id="hero-title">Your story.<br /><em>Your space.</em></h1><p class="hero-description">Một nền tảng để bạn chia sẻ điều mình yêu, khám phá cảm hứng mới và biến từng khoảnh khắc thành dấu ấn riêng.</p><div class="hero-actions"><a class="button button-dark" href="#spaces">Khám phá Reals <span aria-hidden="true">↗</span></a><a class="portfolio-link" href="#portfolio"><span class="play-mark" aria-hidden="true">▶</span> Xem portfolio landing page</a></div></div>
          <div class="hero-visual" aria-label="Bộ sưu tập nội dung Reals"><div class="visual-orbit orbit-one"></div><div class="visual-orbit orbit-two"></div><div class="hero-image hero-image-main"><img src="https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=85" alt="Creator smiling in natural light" /></div><div class="hero-image hero-image-small"><img src="https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=500&q=85" alt="Creative fashion detail" /></div><div class="floating-note"><span class="note-icon">✦</span><span><strong>made for you</strong><small>everyday inspiration</small></span></div><span class="visual-stamp">EST.<br /><strong>2024</strong></span></div>
        </section>
        <section class="ticker" aria-label="Reals highlights"><span>CREATE</span><i>✦</i><span>CONNECT</span><i>✦</i><span>DISCOVER</span><i>✦</i><span>CREATE</span><i>✦</i><span>CONNECT</span></section>
        <section class="spaces-section" id="spaces" aria-labelledby="spaces-title"><div class="section-heading"><p class="eyebrow">Explore your spaces</p><h2 id="spaces-title">Điều gì đang<br /><em>chờ bạn?</em></h2><p>Chọn một không gian để bắt đầu ngày hôm nay.</p></div><div class="space-grid"><a class="space-card space-social" routerLink="/social"><span class="card-number">01</span><span class="card-symbol">◎</span><span><strong>Social</strong><small>Chia sẻ & kết nối</small></span><b aria-hidden="true">↗</b></a><a class="space-card space-video" routerLink="/video"><span class="card-number">02</span><span class="card-symbol">▶</span><span><strong>Video</strong><small>Nhịp sống chuyển động</small></span><b aria-hidden="true">↗</b></a><a class="space-card space-shop" routerLink="/shop"><span class="card-number">03</span><span class="card-symbol">+</span><span><strong>Shop</strong><small>Món đồ có câu chuyện</small></span><b aria-hidden="true">↗</b></a><a class="space-card space-stories" routerLink="/stories"><span class="card-number">04</span><span class="card-symbol">Aa</span><span><strong>Stories</strong><small>Những trang chưa kể</small></span><b aria-hidden="true">↗</b></a></div></section>
        <section class="portfolio-section" id="portfolio" aria-labelledby="portfolio-title"><div class="portfolio-art"><img src="https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1000&q=85" alt="Editorial portrait from the Reals portfolio" /><span>scroll to<br /><strong>explore</strong> ↓</span></div><div class="portfolio-copy"><p class="eyebrow">Portfolio / 01</p><h2 id="portfolio-title">A personal<br /><em>point of view.</em></h2><p>Portfolio landing page hiện đại cho creator, photographer và những người đang xây dựng thương hiệu cá nhân của riêng mình.</p><a class="button button-light" href="#about">Xem case study <span aria-hidden="true">↗</span></a></div></section>
      </main>
      <footer id="about"><span class="wordmark"><span>R</span>reals</span><p>Made to be seen, made to be felt.</p><span class="footer-year">© 2024</span></footer>
    </div>
  `,
  styles: [`
    :host { display: block; min-height: 100vh; }
    .landing-page { --ink: #24231f; --paper: #f4f0e9; --coral: #ec654c; --yellow: #f5ca62; min-height: 100vh; overflow: hidden; background: var(--paper); color: var(--ink); font-family: 'Outfit', sans-serif; }
    .site-nav, main, footer { width: min(1180px, calc(100% - 64px)); margin: auto; }
    .site-nav { height: 88px; display: flex; align-items: center; justify-content: space-between; }
    .wordmark { color: var(--ink); text-decoration: none; font-size: 1.35rem; font-weight: 700; letter-spacing: -.06em; }
    .wordmark > span { display: inline-grid; place-items: center; width: 30px; height: 30px; margin-right: 4px; border-radius: 50%; background: var(--coral); color: white; font-size: 1rem; letter-spacing: 0; }
    .nav-links { display: flex; gap: 34px; margin-left: 100px; }.nav-links a, .nav-action { color: var(--ink); font-size: .78rem; font-weight: 500; text-decoration: none; }.nav-links a { opacity: .64; }.nav-action { padding: 11px 16px; border: 1px solid rgba(36,35,31,.25); border-radius: 100px; }.nav-action span, .button span { margin-left: 9px; }
    .hero { min-height: calc(100vh - 88px); display: grid; grid-template-columns: minmax(0, .9fr) minmax(390px, 1.1fr); align-items: center; gap: 30px; padding: 38px 0 100px; }.eyebrow { display: flex; align-items: center; gap: 9px; margin: 0 0 21px; color: var(--coral); font-size: .68rem; font-weight: 700; letter-spacing: .18em; text-transform: uppercase; }.eyebrow-dot { width: 7px; height: 7px; border-radius: 50%; background: var(--coral); }h1, h2 { margin: 0; font-weight: 500; letter-spacing: -.075em; line-height: .9; }h1 { max-width: 640px; font-size: clamp(4.4rem, 8.8vw, 8.3rem); }h1 em, h2 em { color: var(--coral); font-family: Georgia, serif; font-weight: 400; }.hero-description { max-width: 380px; margin: 34px 0 30px; color: rgba(36,35,31,.67); font-size: .96rem; line-height: 1.65; }.hero-actions { display: flex; align-items: center; flex-wrap: wrap; gap: 24px; }.button { display: inline-flex; align-items: center; border-radius: 100px; padding: 15px 20px; font-size: .78rem; font-weight: 700; text-decoration: none; }.button-dark { background: var(--ink); color: white; }.button-light { background: var(--paper); color: var(--ink); }.portfolio-link { display: inline-flex; align-items: center; gap: 8px; color: var(--ink); font-size: .78rem; font-weight: 700; text-decoration: none; }.play-mark { display: inline-grid; place-items: center; width: 27px; height: 27px; border: 1px solid rgba(36,35,31,.35); border-radius: 50%; font-size: .52rem; }
    .hero-visual { position: relative; min-height: 580px; }.hero-image { position: absolute; overflow: hidden; box-shadow: 0 24px 50px rgba(87,60,39,.17); }.hero-image img, .portfolio-art img { width: 100%; height: 100%; display: block; object-fit: cover; }.hero-image-main { top: 20px; right: 10%; width: min(340px, 66%); height: 480px; border-radius: 180px 180px 5px 5px; transform: rotate(4deg); }.hero-image-small { bottom: 6px; left: 7%; width: 190px; height: 220px; border: 9px solid var(--paper); transform: rotate(-8deg); }.visual-orbit { position: absolute; border: 1px solid rgba(236,101,76,.5); border-radius: 50%; }.orbit-one { top: -10px; right: 4%; width: 420px; height: 420px; }.orbit-two { bottom: 10px; left: -6%; width: 245px; height: 245px; border-color: rgba(245,202,98,.9); }.floating-note { position: absolute; right: 0; bottom: 98px; display: flex; align-items: center; gap: 10px; padding: 12px 15px; background: var(--yellow); color: var(--ink); transform: rotate(5deg); }.note-icon { font-size: 1.3rem; }.floating-note span:last-child { display: flex; flex-direction: column; font-size: .7rem; line-height: 1.2; }.floating-note small { opacity: .65; }.visual-stamp { position: absolute; top: 60px; left: 5%; color: var(--coral); font-size: .6rem; letter-spacing: .12em; line-height: 1.45; transform: rotate(-12deg); }.visual-stamp strong { font-size: 1.15rem; letter-spacing: 0; }
    .ticker { width: 100vw; margin-left: calc((100vw - min(1180px, calc(100% - 64px))) / -2); display: flex; justify-content: center; gap: clamp(20px, 4vw, 70px); padding: 18px 20px; overflow: hidden; background: var(--coral); color: white; font-size: .66rem; font-weight: 700; letter-spacing: .2em; }.ticker i { color: var(--yellow); font-style: normal; }.spaces-section { padding: 130px 0 150px; }.section-heading { display: grid; grid-template-columns: 1fr 1fr 1fr; align-items: end; gap: 30px; margin-bottom: 58px; }.section-heading .eyebrow { align-self: start; }h2 { font-size: clamp(3rem, 6vw, 5.8rem); }.section-heading > p:last-child { max-width: 180px; margin: 0 0 5px; color: rgba(36,35,31,.6); font-size: .85rem; line-height: 1.5; }
    .space-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; }.space-card { min-height: 310px; display: flex; flex-direction: column; justify-content: space-between; padding: 23px; color: var(--ink); text-decoration: none; transition: transform 180ms ease; }.space-card:hover { transform: translateY(-8px); }.space-card > span:last-of-type { display: flex; flex-direction: column; gap: 4px; }.space-card strong { font-size: 1.28rem; font-weight: 500; }.space-card small { font-size: .72rem; opacity: .63; }.card-number { font-size: .65rem; opacity: .6; }.card-symbol { align-self: flex-end; font-size: 4rem; font-weight: 400; line-height: 1; }.space-card b { align-self: flex-end; font-size: 1.15rem; font-weight: 400; }.space-social { background: #b8d8d4; }.space-video { background: #f1c1ae; }.space-shop { background: var(--yellow); }.space-stories { background: #c9c4e7; }
    .portfolio-section { display: grid; grid-template-columns: 1fr 1fr; align-items: center; gap: 10%; padding: 85px 8%; background: var(--ink); color: var(--paper); }.portfolio-art { position: relative; height: 530px; }.portfolio-art img { filter: saturate(.75); }.portfolio-art span { position: absolute; right: -35px; bottom: 28px; padding: 11px; background: var(--yellow); color: var(--ink); font-size: .66rem; line-height: 1.2; transform: rotate(7deg); }.portfolio-art strong { font-size: .85rem; }.portfolio-copy .eyebrow { color: var(--yellow); }.portfolio-copy h2 em { color: var(--yellow); }.portfolio-copy > p:not(.eyebrow) { max-width: 340px; margin: 34px 0; color: rgba(244,240,233,.68); font-size: .9rem; line-height: 1.65; }footer { display: flex; align-items: center; justify-content: space-between; padding: 28px 0; font-size: .72rem; }.footer-year { opacity: .5; }
    @media (max-width: 760px) { .site-nav, main, footer { width: min(100% - 36px, 560px); }.site-nav { height: 70px; }.nav-links { display: none; }.hero { display: flex; flex-direction: column; align-items: stretch; min-height: auto; padding: 72px 0 70px; }.hero-description { margin: 25px 0; }.hero-visual { min-height: 430px; margin-top: -12px; }.hero-image-main { width: 60%; height: 355px; }.hero-image-small { width: 135px; height: 160px; }.orbit-one { width: 300px; height: 300px; }.floating-note { right: 2%; bottom: 50px; }.visual-stamp { top: 28px; }.ticker { width: 100vw; margin-left: -18px; justify-content: flex-start; white-space: nowrap; }.ticker span:nth-of-type(n+4), .ticker i:nth-of-type(n+4) { display: none; }.spaces-section { padding: 88px 0; }.section-heading { display: block; margin-bottom: 38px; }.section-heading h2 { margin-bottom: 20px; }.space-grid { grid-template-columns: repeat(2, 1fr); gap: 9px; }.space-card { min-height: 220px; padding: 17px; }.card-symbol { font-size: 3rem; }.portfolio-section { grid-template-columns: 1fr; gap: 50px; padding: 55px 28px; margin: 0 -18px; }.portfolio-art { height: 330px; }.portfolio-art span { right: -8px; }.portfolio-copy h2 { font-size: 3.5rem; }footer { gap: 12px; } }
    @media (max-width: 380px) { h1 { font-size: 3.8rem; }.hero-actions { align-items: flex-start; flex-direction: column; gap: 16px; }.space-card { min-height: 200px; }.site-nav { padding: 0 2px; } }
  `],
})
export class HomeComponent {
  private authService = inject(AuthService);
  private router = inject(Router);

  get userDisplayName() {
    const user = this.authService.user();
    return user?.displayName || user?.username || user?.email || 'creator';
  }

  logout() {
    this.authService.logout();
    this.router.navigate(['/auth/login']);
  }
}
